style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/fastly/sidekiq-prometheus
options:
  commits:
    filters:
      Type:
        - feat
        - fix
  commit_groups:
    title_maps:
      feat: Features
      doc: Documentation
      fix: Bug Fixes
  refs:
    actions:
      - Closes
      - Fixes
  issues:
    prefix:
      - #
  header:
    pattern: "^(\\w*)\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
